### ISSUE TITLE
Python 3.9 support (wheel missing)

### ISSUE THREAD

**Issue by lil-O** [letmaik/pyvirtualcam#10]
Failing to install dont know why

**Comment by letmaik** [comment]
More details please. OS and Python version.

**Comment by lil-O** [comment]
windows 10 
Python 3.9.0

**Comment by letmaik** [comment]
Is this 32bit or 64bit python? 32 bit is unsupported. If it's 64 bit, can you paste the complete output when running pip install?

**Comment by letmaik** [comment]
Just realized that the latest version of this library wasn't released for Python 3.9 yet. So that's the issue. You can check that here: https://pypi.org/project/pyvirtualcam/#files I'll do a new release with Python 3.9 wheels.

**Comment by letmaik** [comment]
Python 3.9 wheel is out now.
