### ISSUE TITLE
OBS plugin used from local folder

### ISSUE THREAD

**Issue by msj121** [letmaik/pyvirtualcam#105]
Is there a way to use the obs plugin from a local folder instead of loading it from the ~/Library folder. This would bypass the need for the user to install obs as it can be packaged with the python app in relative folder.

Thanks! This would help me a lot.

**Comment by letmaik** [comment]
You need admin permissions to install the DAL plugin (copying to `/Library/CoreMediaIO/Plug-Ins/DAL`), so I guess in theory it may work. Feel free to experiment with it but I won't support this method as an official approach as it requires poking into OBS' distribution package and doing low-level operations, something that can easily be messed up.
