### ISSUE TITLE
有可能加入声音也一起推送吗？

### ISSUE THREAD

**Issue by funnys1r** [letmaik/pyvirtualcam#113]
有可能加入声音也一起推送吗？

**Comment by letmaik** [comment]
@funnys1r Please use English as universal language :) I translated your question with Google and it said "Is it possible to add sounds and push them together?" I'm assuming you're asking whether it is possible to output audio in addition to the video frames through the virtual camera. No, that's not possible. Maybe you find some inspiration here: https://superuser.com/questions/603294/is-there-a-program-that-allows-me-to-send-audio-output-to-a-microphone-input-ei

**Comment by funnys1r** [comment]
Anyway, thank you for the program you designed
