### ISSUE TITLE
Feature Request: Build for Linux aarch64/arm64 on PyPI

### ISSUE THREAD

**Issue by marty-sullivan** [letmaik/pyvirtualcam#122]
Hello,

There is currently no way to install this on linux running arm64 via PyPI. I'd like to request this additional build given there are many arm-based linux systems now. Or, perhaps at least adding the source package to PyPI so that it can be built from source via pip.

Thanks

EDIT: I did confirm I can build from source by doing `pip install git+https://github.com/letmaik/pyvirtualcam.git` so even just making sure that the source tar.gz is available as an option on PyPI is sufficient.

**Comment by letmaik** [comment]
That should be possible, care to submit a PR? You can get inspiration from here: https://github.com/letmaik/rawpy/blob/d368d56f2eb9e7bd1f4c2f783bc4873d177e321b/.github/workflows/ci.yml#L73

**Comment by agilebean** [comment]
This would be really a valuable PR. Can anybody do this?

In the meantime, how would I create this on my own?

**Comment by letmaik** [comment]
@marty-sullivan Do you want to take this on? Shouldn't be much effort.

**Comment by agilebean** [comment]
@marty-sullivan thanks a lot. 
i tried 'pip install git+<repo>' and it worked.
