### ISSUE TITLE
Not installable on python 32Bit

### ISSUE THREAD

**Issue by derchipo** [letmaik/pyvirtualcam#13]
I tried to install pyvirtualcam on python 3.9 32bit with command pip install pyvirtualcam.

ERROR: Could not find a version that satisfies the requirement pyvirtualcam
ERROR: No matching distribution found for pyvirtualcam

**Comment by letmaik** [comment]
I generally don't support 32bit anymore on my packages. Is there a reason you can't switch to 64bit python?

**Comment by derchipo** [comment]
Thanks for your answer. Yes it is. I want to use it on 32 and 64 Bit. In the description you write somthing about the registration of 32-Bit Obs-Cam. This is the reason why I tought that the pyvirtualcam also support it.

**Comment by letmaik** [comment]
You can use the virtual camera (obs-virtual-cam) in 32 bit and 64 bit apps, but the Python package can only be used in 64 bit Python. So in a way this is a non-issue, just run your Python code in a 64 bit Python and all is fine.

**Comment by derchipo** [comment]
Thanks. Is it possible for me to get functionality for 32 bit? That would help me a lot.
