### ISSUE TITLE
can't set output resolution

### ISSUE THREAD

**Issue by derchipo** [letmaik/pyvirtualcam#14]
Thanks vor this lib. It works fine for me. But there ist one Problem

After multiple tests it is not possible to set the outputresolution.

cam = pyvirtualcam.Camera(width=1920, height=1080, fps=18, print_fps=True)
cam = pyvirtualcam.Camera(width=1280, height=720, fps=18, print_fps=True)
cam = pyvirtualcam.Camera(width=768, height=432, fps=18, print_fps=True)
cam = pyvirtualcam.Camera(width=480, height=270, fps=18, print_fps=True)
and all with 
cam = pyvirtualcam.Camera(480, 270, fps=18, print_fps=True)
all of these inits procuces the same Output: 1920x1080 with very large img sizes
How can I reduce the Quality to get a better stream with bad uploadspeed.
Or how can i set the default output resolution.

**Comment by derchipo** [comment]
Hi,

 

the latest verion is not working form me.

 

When i have instelled OBS Studio pyvirtualcam in version 0.5 uses the OBS-Virtual-Camera and not the OBS-Camera wich i registerd.

In Version 0.34 it works but there i have the problem setting the outputreolution

 

 

 

Von: Maik Riechert ***@***.***> 
Gesendet: Mittwoch, 10. März 2021 21:46
An: letmaik/pyvirtualcam ***@***.***>
Cc: derchipo ***@***.***>; Author ***@***.***>
Betreff: Re: [letmaik/pyvirtualcam] can't set output resolution (#14)

 

Could you try again with the latest version? Also, could you make sure to first start the Python script and only then use the camera in other apps?

**Comment by letmaik** [comment]
Can you check the README? There have been some changes in newer versions.

**Comment by derchipo** [comment]
Yes,

 

i saw that in the new version the lib select the first avalable device. This crashes my script when i habeOBS-Studio installed. Maybee it’s a bug ? 

 

Von: Maik Riechert ***@***.***> 
Gesendet: Dienstag, 16. März 2021 18:37
An: letmaik/pyvirtualcam ***@***.***>
Cc: derchipo ***@***.***>; Author ***@***.***>
Betreff: Re: [letmaik/pyvirtualcam] can't set output resolution (#14)

 

Can you check the README? There have been some changes in newer versions.
