### ISSUE TITLE
Use permissive license

### ISSUE THREAD

**Issue by letmaik** [letmaik/pyvirtualcam#4]
pyvirtualcam bundles code from https://github.com/Fenrirthviti/obs-virtual-cam (fork of https://github.com/CatxFish/obs-virtual-cam) in `pyvirtualcam/native_windows/queue/`, which is GPL-2. This is why pyvirtualcam itself is GPL-2.

I opened https://github.com/CatxFish/obs-virtual-cam/issues/115 asking whether the license could be changed to something more permissive.

**Comment by letmaik** [comment]
The new macOS port also includes GPL code (from OBS / obs-mac-virtualcam). Closing this issue as it's unlikely upstream will change their license.

**Comment by Pandinosaurus** [comment]
Hi letmaik,

Would it be acceptable to create an OBS-free branch of pyvirtualcam with e.g., a MIT License ?
