### ISSUE TITLE
Sending ARGB Frames

### ISSUE THREAD

**Issue by graphemecluster** [letmaik/pyvirtualcam#46]
I am sorry to open an issue here but I am trying to send ARGB data (with shape `(h,w,4)`) to OBS but it seems that neither the shape is correct nor the OBS Virtual Camera support ARGB data. I've asked a question on [StackOverflow](https://stackoverflow.com/questions/66854423/) but I think no one would be able to answer my question, so I decided to ask here. Any help would be much appreciated.

**Comment by letmaik** [comment]
Out of curiosity, where are you getting your ARGB frames from?
In any case, you can easily convert ARGB to RGB with `frame[:,:,1:]`, or `frame[:,:,:-1]` for RGBA.

**Comment by letmaik** [comment]
(Virtual) webcams generally don't support transparency, as far as I know. The native format of the OBS virtual camera on Windows is NV12 and UVYV on macOS, both of which don't have an alpha channel.

**Comment by letmaik** [comment]
I'm not too knowledgeable on OBS itself, but the virtual camera device itself really doesn't support alpha.

**Comment by graphemecluster** [comment]
OK, I’ll find others for help or try another way then. Thank you for your replies!
