### ISSUE TITLE
load dll failed

### ISSUE THREAD

**Issue by gangjiang1989** [letmaik/pyvirtualcam#6]
After installing pyvirtualcam: 
when I import the package as:  import pyvirtualcam
always show :
  File "C:\Python37_64\lib\site-packages\pyvirtualcam\__init__.py", line 3, in <module>
    from .camera import Camera
  File "C:\Python37_64\lib\site-packages\pyvirtualcam\camera.py", line 11, in <module>
    from pyvirtualcam import _native_windows
ImportError: DLL load failed: The specified module could not be found.

Do I need put any other dll in the system path？

Env: 
WIndows 10
python 3.7.9 64bit
OBS-VirtualCam 2.0.4

use command:
regsvr32 /n /i:1 "obs-virtualcam\bin\32bit\obs-virtualsource.dll"
regsvr32 /n /i:1 "obs-virtualcam\bin\64bit\obs-virtualsource.dll"

**Comment by letmaik** [comment]
Can you share more about how you installed the package and the exact commands for running it? Also, include details like current folder in your shell.

**Comment by gangjiang1989** [comment]
thanks for your reply, I remove all the python and reinstall it and pyvirtualcam, works fine now.
