### ISSUE TITLE
PixelFormat.RGBA

### ISSUE THREAD

**Issue by babydickdanilko** [letmaik/pyvirtualcam#63]
- Operating system: WIN 10
- pyvirtualcam version: 0.8.0
- Virtual camera (OBS, v4l2loopback, UnityCapture):  OBS
- Virtual camera version: 2.0.4

**Describe the bug**
When im used PixelFormat.RGBA im get traceback RuntimeError: 'obs' backend: Unsupported image format.

**To Reproduce**
https://github.com/letmaik/pyvirtualcam/blob/master/samples/rgba_gif.py

**Comment by letmaik** [comment]
The error is correct, RGBA is only supported in the Unity Capture camera.

**Comment by babydickdanilko** [comment]
> The error is correct, RGBA is only supported in the Unity Capture camera.

Thanks for the answer. Is it possible to open a gif in RGB through imageio?

**Comment by letmaik** [comment]
Please ask this over in the imageio issues or stackoverflow.
