### ISSUE TITLE
Multiple OBS Virtual cameras in OBS - using additional obs-virtual-cam plugin

### ISSUE THREAD

**Issue by jedi4ever** [letmaik/pyvirtualcam#66]
Hi wanted to drop this note about having multiple OBS Virtual cameras.

Since Virtual Camera has been integrated in the OBS code base one can only activate a single virtual camera.

This plugin - https://github.com/Fenrirthviti/obs-virtual-cam (a fork from the original plugin) allows you to add 4 more. It works with latest version of OBS fine and just adds 4 extra cameras. (Windows).

Thanks again for writing this library and the documentation.

**Comment by letmaik** [comment]
Keep in mind that pyvirtualcam only works with the built-in OBS virtual camera. So if you install the plugin you mentioned then you can use those extra cameras from within OBS as output, but you can't use them within pyvirtualcam for example to output to  multiple cameras simultaneously.
As described in the README you can also use Unity Capture for pyvirtualcam and then use the built-in camera in OBS for further composition / final output. Also, the latency of the built-in camera as well as Unity Capture is much lower than the OBS plugin you mentioned.
I agree though that you need to use the plugin if you want to output multiple virtual cameras at once from within OBS.
What is your use case exactly?

**Comment by jedi4ever** [comment]
I use opencv & pyvirtual to write to virtual camera 1.
At the same I use this as a camera device in OBS to mix in other elements and use the switch over to scenes.
Then I use one of the virtual camera provided by the plugin I mention to output OBS as a virtual camera and use it in Zoom.

**Comment by letmaik** [comment]
Is there anything that should be changed in the README? Otherwise I'm going to close this.
