### ISSUE TITLE
 Error when running setup.py

### ISSUE THREAD

**Issue by Rich-Lily** [letmaik/pyvirtualcam#68]
When I run setup.py on Windows 10, I always have the following problem:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DVERSION_INFO="0.8.0" -Ipyvirtualcam/native_windows_obs -Ic:\users\administrator\pyvirtualcam.eggs\pybind11-2.7.1-py3.8.egg\pybind11\include -Iexternal/libyuv/include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python38\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include" "-IC:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt" /EHsc /Tppyvirtualcam/native_windows_obs/main.cpp /Fobuild\temp.win-amd64-3.8\Release\pyvirtualcam/native_windows_obs/main.obj /EHsc /std:c++17
Cl: command line warning D9002: ignore unknown option "/ STD :c++17"
main.cpp
pyvirtualcam/native_windows_obs/main.cpp(2): fatal error C1083: 无法打开包括文件: “optional”: No such file or directory
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe' failed with exit status 2

May I ask how to solve these problems? Looking forward to your reply!

**Comment by letmaik** [comment]
Any reason you're trying to build from source? The published binary wheels should be good enough for most platforms: `pip install pyvirtualcam`. To answer your question though, your Visual Studio version seems too old.
