### ISSUE TITLE
Alpha channel supported now?

### ISSUE THREAD

**Issue by kevinpl07** [letmaik/pyvirtualcam#83]
_Originally posted by @graphemecluster in https://github.com/letmaik/pyvirtualcam/discussions/51_

In reference to this issue, is rgba now supported?

**Comment by letmaik** [comment]
Please use Discussions for questions in the future, as guided towards in the New Issue landing page.

Regarding your question, it's all in the README ;) https://github.com/letmaik/pyvirtualcam#windows-unity-capture. And there's even an example at https://github.com/letmaik/pyvirtualcam/blob/main/examples/rgba_gif.py.
