### ISSUE TITLE
Wheels for macOS ARM64

### ISSUE THREAD

**Issue by rickwierenga** [letmaik/pyvirtualcam#97]
- Operating system: macOS
- Python version: 3.10.6
- pyvirtualcam version: -
- Virtual camera (OBS, v4l2loopback, UnityCapture): -
- Virtual camera version: -

**Describe the bug**

```
$ pip install pyvirtualcam
ERROR: Could not find a version that satisfies the requirement pyvirtualcam (from versions: none)
ERROR: No matching distribution found for pyvirtualcam
```

Related issue: https://github.com/letmaik/pyvirtualcam/issues/15.

Could this be because of M1?

**Comment by letmaik** [comment]
M1 supports both x86-64 (Intel) and ARM64. So if you use an x86-64 Python installation, then you can install pyvirtualcam via PyPI. I'll keep this issue open to track the publication of PyPI wheels for macOS ARM64. The main blocker currently is GitHub Actions which doesn't support ARM64 (wheels are produced and published within Actions).

**Comment by Iapetus-11** [comment]
I would also like to use pyvirtualcam on M1 and am having the same issue. Is there any workaround for this? 

Also, I found https://github.com/pypa/cibuildwheel which supports M1. Perhaps pyvirtualcam could switch to that for building wheels?

**Comment by nineclicks** [comment]
> I would also like to use pyvirtualcam on M1 and am having the same issue. Is there any workaround for this?
> 
> Also, I found https://github.com/pypa/cibuildwheel which supports Apple silicon. Perhaps pyvirtualcam could switch to that for building wheels?

Use the build from source directions at the bottom of the readme. I have the grayscale animation running on an M1 with obs virtual camera, took only a few seconds to install.

**Comment by cansik** [comment]
Would it make sense to provide the source package as well on PyPi? Because the following works great on an M1:

```
pip install git+https://github.com/letmaik/pyvirtualcam
```

**Comment by letmaik** [comment]
@cansik I generally don't publish source packages anymore for any of my binary Python packages as those more often than not lead to failed builds with obscure error messages and more people complaining and I don't have the time to handle the support requests. I treat building from source as an advanced use case that shouldn't happen by accident (pip automatically falls back to source packages if there are no binary wheels for the target Python version and/or platform, which is unfortunate).

**Comment by cansik** [comment]
@letmaik Thanks for your explanation and I can understand that of course. I solved it now by including the following lines into the requirements of my project. On MacOS arm64, the library will be installed from source, otherwise from the prebuilt wheel.

```
git+https://github.com/letmaik/pyvirtualcam; platform_system == "Darwin" and platform.machine == "arm64"
pyvirtualcam; platform_system != "Darwin" or platform.machine != "arm64"
```

**Comment by lucasmen9527** [comment]
> Would it make sense to provide the source package as well on PyPi? Because the following works great on an M1:
> 
> ```
> pip install git+https://github.com/letmaik/pyvirtualcam
> ```

Thank you i use it successful

**Comment by XinBow99** [comment]
> Would it make sense to provide the source package as well on PyPi? Because the following works great on an M1:
> 
> ```
> pip install git+https://github.com/letmaik/pyvirtualcam
> ```

work for me.
